### ISSUE TITLE
Provide information if thread is question and when it was answered

### ISSUE THREAD

**Issue by lkrzyzanek** [jbossorg/sbs-bulkdataapi#3]
Also information about correct/helpful answer could be provided.

**Comment by lkrzyzanek** [comment]
Each item would have `thread_info` object with following:

				"thread_info"    : {
				    "question"      : true or false,
				    "answered"      : "timestamp if available"
				}

**Comment by lkrzyzanek** [comment]
Implemented. Can be tested here: https://developer-dev.jboss.org/data-api/content.jspa?spaceId=2191&type=forum

**Comment by unibrew** [comment]
Is there an option to enclose also information about helpful/correct answer? On contributions report we have counts of helpful/correct answers.

**Comment by lkrzyzanek** [comment]
Let's cover it in #8
