### ISSUE TITLE
/data-api/spaces.jspa should return all space IDs not only the top level

### ISSUE THREAD

**Issue by unibrew** [jbossorg/sbs-bulkdataapi#9]
It seems that the /data-api/spaces.jspa service returns only top level space IDs, without the whole tree of their children. It's very needed to be able to get them as well either by the default response from the service or by some additional parameter to the service telling it whether the response should be with or without the children.

**Comment by lkrzyzanek** [comment]
Looks like JAVA API changed over Jive versions
